use laserstream_core_proto::{geyser::*, prost::Message};

#[test]
fn triton_bank_id_independent_wire_vectors() {
    // Triton's exact field numbers, not bytes generated by our schema.
    for value in [None, Some(0), Some(1), Some(u64::MAX)] {
        macro_rules! optional {
            ($ty:ty, $tag:expr) => {{
                let bytes = bank_wire($tag, value);
                let decoded = <$ty>::decode(bytes.as_slice()).unwrap();
                assert_eq!(decoded.bank_id, value);
                assert_eq!(decoded.encode_to_vec(), bytes);
            }};
        }
        macro_rules! scalar {
            ($ty:ty, $tag:expr) => {{
                let bytes = bank_wire($tag, value);
                let decoded = <$ty>::decode(bytes.as_slice()).unwrap();
                assert_eq!(decoded.bank_id, value.unwrap_or(0));
                let canonical = bank_wire($tag, value.filter(|v| *v != 0));
                assert_eq!(decoded.encode_to_vec(), canonical);
            }};
        }
        optional!(SubscribeUpdateAccount, 4);
        optional!(SubscribeUpdateSlot, 5);
        scalar!(SubscribeUpdateTransaction, 3);
        scalar!(SubscribeUpdateTransactionStatus, 6);
        scalar!(SubscribeUpdateBlock, 14);
        scalar!(SubscribeUpdateBlockMeta, 10);
        scalar!(SubscribeUpdateEntry, 7);
    }
}

#[cfg(feature = "plugin")]
#[test]
fn all_bank_ids_survive_custom_encoder_and_reverse_conversion() {
    use laserstream_core_proto::plugin::filter::message::FilteredUpdate;
    for bank in [None, Some(0), Some(1), Some(u64::MAX)] {
        let scalar = bank.unwrap_or(0);
        let account = SubscribeUpdateAccountInfo {
            pubkey: vec![1; 32],
            owner: vec![2; 32],
            transaction_index: u64::MAX,
            ..Default::default()
        };
        let transaction = SubscribeUpdateTransactionInfo {
            signature: vec![3; 64],
            transaction: Some(Default::default()),
            meta: Some(Default::default()),
            index: 42,
            ..Default::default()
        };
        let entry = SubscribeUpdateEntry {
            slot: 100,
            bank_id: scalar,
            hash: vec![4; 32],
            index: 3,
            ..Default::default()
        };
        let updates = [
            subscribe_update::UpdateOneof::Account(SubscribeUpdateAccount {
                slot: 100,
                bank_id: bank,
                account: Some(account.clone()),
                ..Default::default()
            }),
            subscribe_update::UpdateOneof::Slot(SubscribeUpdateSlot {
                slot: 100,
                bank_id: bank,
                ..Default::default()
            }),
            subscribe_update::UpdateOneof::Transaction(SubscribeUpdateTransaction {
                slot: 100,
                bank_id: scalar,
                transaction: Some(transaction.clone()),
            }),
            subscribe_update::UpdateOneof::TransactionStatus(SubscribeUpdateTransactionStatus {
                slot: 100,
                bank_id: scalar,
                signature: vec![3; 64],
                index: 42,
                ..Default::default()
            }),
            subscribe_update::UpdateOneof::Entry(entry.clone()),
            subscribe_update::UpdateOneof::BlockMeta(SubscribeUpdateBlockMeta {
                slot: 100,
                bank_id: scalar,
                ..Default::default()
            }),
            subscribe_update::UpdateOneof::Block(SubscribeUpdateBlock {
                slot: 100,
                bank_id: scalar,
                accounts: vec![account],
                transactions: vec![transaction],
                entries: vec![entry],
                ..Default::default()
            }),
        ];
        for update in updates {
            let expected = SubscribeUpdate {
                filters: vec!["all".into()],
                update_oneof: Some(update),
                created_at: Some(Default::default()),
            };
            let filtered = FilteredUpdate::from_subscribe_update(expected.clone()).unwrap();
            assert_eq!(filtered.as_subscribe_update(), expected);
            assert_eq!(filtered.encoded_len(), expected.encoded_len());
            assert_eq!(filtered.encode_to_vec(), expected.encode_to_vec());
            assert_eq!(
                SubscribeUpdate::decode(filtered.encode_to_vec().as_slice()).unwrap(),
                expected
            );
        }
    }
}

fn bank_wire(tag: u8, value: Option<u64>) -> Vec<u8> {
    let Some(mut value) = value else {
        return vec![];
    };
    let mut result = vec![tag << 3];
    while value > 127 {
        result.push((value as u8 & 127) | 128);
        value >>= 7;
    }
    result.push(value as u8);
    result
}
