use yellowstone_grpc_proto::{geyser::*, prost::Message};

#[test]
fn triton_bank_id_independent_wire_vectors() {
    // Triton's exact field numbers, not bytes generated by our schema.
    for value in [None, Some(0), Some(1), Some(u64::MAX)] {
        macro_rules! optional {
            ($ty:ty, $tag:expr) => {{
                let bytes = bank_wire($tag, value);
                let decoded = <$ty>::decode(bytes.as_slice()).unwrap();
                assert_eq!(decoded.bank_id, value);
                assert_eq!(decoded.encode_to_vec(), bytes);
            }};
        }
        macro_rules! scalar {
            ($ty:ty, $tag:expr) => {{
                let bytes = bank_wire($tag, value);
                let decoded = <$ty>::decode(bytes.as_slice()).unwrap();
                assert_eq!(decoded.bank_id, value.unwrap_or(0));
                let canonical = bank_wire($tag, value.filter(|v| *v != 0));
                assert_eq!(decoded.encode_to_vec(), canonical);
            }};
        }
        optional!(SubscribeUpdateAccount, 4);
        optional!(SubscribeUpdateSlot, 5);
        scalar!(SubscribeUpdateTransaction, 3);
        scalar!(SubscribeUpdateTransactionStatus, 6);
        scalar!(SubscribeUpdateBlock, 14);
        scalar!(SubscribeUpdateBlockMeta, 10);
        scalar!(SubscribeUpdateEntry, 7);
    }
}

#[test]
fn nested_block_entry_preserves_independent_bank_and_legacy_fields() {
    for value in [None, Some(0), Some(1), Some(u64::MAX)] {
        // Entry: slot=100, index=3, starting_transaction_index=42.
        let mut entry_bytes = vec![0x08, 100, 0x10, 3, 0x30, 42];
        entry_bytes.extend(bank_wire(7, value));
        // Block: slot=100, entries (tag 13); bank deliberately differs from entry.
        let mut block_bytes = vec![0x08, 100, 0x6a, entry_bytes.len() as u8];
        block_bytes.extend(entry_bytes);
        block_bytes.extend(bank_wire(14, Some(99)));
        // SubscribeUpdate.block (tag 5).
        let mut update_bytes = vec![0x2a, block_bytes.len() as u8];
        update_bytes.extend(block_bytes);
        let decoded = SubscribeUpdate::decode(update_bytes.as_slice()).unwrap();
        let Some(subscribe_update::UpdateOneof::Block(block)) = &decoded.update_oneof else {
            panic!("expected block");
        };
        assert_eq!(block.slot, 100);
        assert_eq!(block.bank_id, 99);
        assert_eq!(block.entries.len(), 1);
        assert_eq!(block.entries[0].slot, 100);
        assert_eq!(block.entries[0].index, 3);
        assert_eq!(block.entries[0].starting_transaction_index, 42);
        assert_eq!(block.entries[0].bank_id, value.unwrap_or(0));
        assert_eq!(
            SubscribeUpdate::decode(decoded.encode_to_vec().as_slice()).unwrap(),
            decoded
        );
    }
}

fn bank_wire(tag: u8, value: Option<u64>) -> Vec<u8> {
    let Some(mut value) = value else {
        return vec![];
    };
    let mut result = vec![tag << 3];
    while value > 127 {
        result.push((value as u8 & 127) | 128);
        value >>= 7;
    }
    result.push(value as u8);
    result
}
