name: "Sync helius from upstream rpcpool"

on:
  #  push:
  schedule:
    - cron: "00 19 * * 1-5"
  workflow_dispatch:
  pull_request:
jobs:
  git-sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/rpcpool/yellowstone-grpc"
          destination_repo: "https://github.com/helius-labs/yellowstone-grpc"
          source_branch: "refs/remotes/source/*"
          destination_branch: "refs/heads/*"
          git_config: |
            user.name=GitHub Actions
            user.email=actions@github.com
  git-sync-tags:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/rpcpool/yellowstone-grpc"
          destination_repo: "https://github.com/helius-labs/yellowstone-grpc"
          source_branch: "refs/remotes/source/*"
          destination_branch: "refs/heads/*"
          git_config: |
            user.name=GitHub Actions
            user.email=actions@github.com
  git-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: git-rebase
        uses: tiacsys/git-rebase@v1.0.1
        with:
          repo: "https://github.com/rpcpool/yellowstone-grpc"
          source_branch: "master"
          destination_branch: "master"
          git_config: |
            user.name=GitHub Actions
            user.email=actions@github.com