name: "Sync helius from upstream rpcpool"

on:
  #  push:
  schedule:
    - cron: "00 19 * * 1-5"
  workflow_dispatch:
  pull_request:
jobs:
  git-sync-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          submodules: recursive
          fetch-depth: 0
      - name: Setup email
        run: |
          git config --global user.email "liam@helius.xyz"
          git config --global user.name "Helius Infrastructure"
      - name: Add upstream
        run: git remote add upstream https://github.com/rpcpool/yellowstone-grpc
      - name: Fetch upstream
        run: git fetch --all --tags
      - name: rebase master
        run: git pull upstream master --rebase
      - name: pull origin
        run: git pull origin master
      - name: push all
        run: git push origin --all
      - name: push tags
        run: git push origin --tags
